### ISSUE TITLE
Windows Illegal Instruction Release Mode

### ISSUE THREAD

**Issue by GGist** [carllerche/iovec#4]
Hi,

I have been using this crate via the `tokio`/`bytes` crates and after rust `1.19`, I am getting illegal instruction errors when running in release mode. The following snippet fails in release mode:
```
extern crate iovec;

use iovec::IoVec;

fn main() {
    let iovec: &IoVec = Default::default();
}
```
with error:
```error: process didn't exit successfully: `target\release\asd.exe` (exit code: 3221225501)
Illegal instruction```

However, the following snippet succeeds in release mode:
```
extern crate iovec;

use iovec::IoVec;

fn main() {
    let buffer: &[u8] = Default::default();
    let iovec: &IoVec = buffer.into();
}
```

Both of the previous examples were run with `lto = false`. However, when setting `lto = true`, the first example succeeds while the second one fails.

I wasnt sure if I should report this to the rust repo, as I wasnt sure as to the guarantees of ub when transmuting some type (WSABUF) to [u8] that doesnt follow the actual layout of a [u8].

Platform (Windows 10):
```
rustc 1.20.0 (f3d6973f4 2017-08-27)
binary: rustc
commit-hash: f3d6973f41a7d1fb83029c9c0ceaf0f5d4fd7208
commit-date: 2017-08-27
host: x86_64-pc-windows-msvc
release: 1.20.0
LLVM version: 4.0
```

**Comment by alexcrichton** [comment]
Thanks for the report! I've posted a PR in #5 along with a description of what I believe the issue is.
