### ISSUE TITLE
Reissue the recent 0.1.1 as 0.2.0

### ISSUE THREAD

**Issue by jolhoeft** [carllerche/iovec#6]
Would it be possible to have the recent 0.1.1 pulled and republished as 0.2.0? The change is causing panics in dependencies of my dependencies. I expect it will take some time to get everything updated to the new api, and this would  keep 'cargo update' useful.

**Comment by alexcrichton** [comment]
Thanks for the report! While this was an unfortunate breaking change it was made due to soundness concerns, so the choice here is either a segfault at runtime or a program that doesn't compile, so it was figured that the halted compilation is probably preferred...

**Comment by alexcrichton** [comment]
er, segfault or panic*

**Comment by jolhoeft** [comment]
Panic, I posted a backtrace in https://github.com/carllerche/mio/issues/746, which I see you've already created a PR to fix. Thank you.

My personal preference for this kind of issue is to break the build with a version increment. That catches these issues at compile time as opposed to run time, where it can be much more of a challenge. Cargo lets you lock to a specific version if you need to defer upgrading.

That said, since you've addressed this in mio, and there are not many other packages depending on this, we could probably called this fixed.

**Comment by carllerche** [comment]
The generally accepted rule of thumb is that soundness fixes should be pushed out as patch releases even if they are breaking changes (though this breakage should be minimized as much as possible).

As such, I think this issue doesn't require any further action.
